### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by wind91725** [ronghanghu/vqa-maskrcnn-benchmark-m4c#1]
您好，我正在学习你的m4c项目https://github.com/ronghanghu/pythia.
我想通过extract_features_vmb.py ，extract_ocr_frcn_feature.py去获取图片的特征，是不是要先安装
vqa-maskrcnn-benchmark-m4c这个项目？
能给点指导吗，十分感谢！

**Comment by ronghanghu** [comment]
是的，需要先安装vqa-maskrcnn-benchmark-m4c才能使用extract_ocr_frcn_feature.py。

安装步骤如下：
```
git clone https://github.com/ronghanghu/vqa-maskrcnn-benchmark-m4c.git
cd vqa-maskrcnn-benchmark-m4c
python setup.py build develop
```

**Comment by wind91725** [comment]
非常感谢您的回复，但我在调试https://github.com/ronghanghu/pythia.代码中，遇见如下错误

**Comment by wind91725** [comment]
非常感谢您的回复，我在调试https://github.com/ronghanghu/pythia.时遇见下面错误：

**Comment by wind91725** [comment]
非常感谢您的回复，我在调试代码中，碰到下面的错误：

  File "tools/run.py", line 88, in <module>
    run()
  File "tools/run.py", line 75, in run
    trainer.load()
  File "/data/home/share1/pythia/pythia/trainers/base_trainer.py", line 49, in load
    self.load_extras()
  File "/data/home/share1/pythia/pythia/trainers/base_trainer.py", line 146, in load_extras
    self.checkpoint = Checkpoint(self)
  File "/data/home/share1/pythia/pythia/utils/checkpoint.py", line 51, in __init__
    self.repo = git.Repo(self.repo_path)
  File "/data/home/share1/36/anaconda3/envs/pythia/lib/python3.6/site-packages/git/repo/base.py", line 181, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /data/home/share1/pythia

请问有什么解决的方法吗？

**Comment by wind91725** [comment]
非常感谢您的回复，谢谢！

**Comment by wind91725** [comment]
还有一个问题想请教您，我想基于您的项目https://github.com/ronghanghu/pythia. 做成一个交互式的界面，想请问下 下面这段代码中 batch里的特征是怎么转过来的呀，没看懂dataload的代码
    def predict_for_evalai(self, dataset_type):
        reporter = self.dataset_loader.get_test_reporter(dataset_type)
        with torch.no_grad():
            self.model.eval()
            message = "Starting {} inference for evalai".format(dataset_type)
            self.writer.write(message)

            while reporter.next_dataset():
                dataloader = reporter.get_dataloader()
                for batch in tqdm(dataloader):
                    prepared_batch = reporter.prepare_batch(batch)
                    # print(prepared_batch)
                    model_output = self.model(prepared_batch)
                    report = Report(prepared_batch, model_output)
                    # print(report)
                    results = reporter.add_to_report(report)
                    print(results)
